### PR TITLE
II and III level made

### PR DESCRIPTION
**Pull request by dmitryakimov2206283**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Dmitry.

Level I. 
Task 4: At x ==0 s should be = cos(0), isn't it?
if (x == 0)
                {
                    Console.WriteLine("Entered data is wrong");
                    return;
                }
Level II. Excellent!
Level III. Task 1. 
Factorial should be calculated as (2i)! You calculate as i!
Task 3.
s = 0; & s += 1; in the end. Why not just  s = 1?

Make small adjustments and write a comment to this request. No need to create new one.

You have 3 attempts left.

**Comment by dmitryakimov2206283** [comment]
So I made these adjustments except first (Level I, Task 4). If I change the condition to `x == cos(0)` it allows me to enter 0 (because cos(0) is 1) and zero-division appears.

For Level III, Task 1 I changed factorial calculation formula to calculate it as 2i.
```c#
#region Task 1
Console.WriteLine("Task 1:");
double xfPower2;
double xfPowerSum;
double term;
double y;
int factAddend;

for (decimal xf = 0.1m; xf <= 1; xf += 0.1m)
{
    s = 0;
    sign = -1;
    fact = 1;
    factAddend = 0;

    xfPower2 = (double)(xf * xf);
    xfPowerSum = xfPower2;

    // Zero term calculation
    term = xfPower2;
    s += term;

    for (int i = 1; term >= 0.0001; i++)
    {
        sign = -sign;

        // i = 1; fact = 1 * 2 => fact = (i + 0) * (i + 1)
        // i = 2; fact *= 3 * 4 => fact *= (i + 1) * (i + 2)
        // i = 3; fact *= 5 * 6 => fact *= (i + 2) * (i + 3)
        // i = 4; fact *= 7 * 8 => fact *= (i + 3) * (i + 4)
        // i = 5; fact *= 9 * 10 => fact *= (i + 4) * (i + 5)
        // i = 6; fact *= 11 * 12 => fact *= (i + 5) * (i + 6)
        fact *= (i + factAddend) * (i + factAddend + 1);

        term = xfPowerSum / fact;
        s += term * sign;

        xfPowerSum *= xfPower2;
        factAddend++;
    }

    y = Math.Cos((double)xf);

    Console.WriteLine($"x = {xf} \t y = {Math.Round(y, 3)} \t   s = {Math.Round(s, 3)}");
}
#endregion
```

For Level III, Task 3 I simplified s = 0 & s += 1 to just s = 1.
```c#
...
for (decimal xf = 0.1m; xf <= 1; xf += 0.1m)
{
    s = 1; // s = 0 & s += 1 simplified to this line
    fact = 1;

    term = 1;

    for (int i = 1; term >= 0.0001; i++)
    {
        fact *= i;
        term = Math.Cos((double)(i * xf)) / fact;

        s += term;
    }
...
```

**Comment by NemirovichMark** [comment]
Hello Dmitry!

Level III, Task 3 done right 👍 
Level I, Task 4: 
You can make 2 conditions: if (x>0) {} else If(x==0) {}. Then problem will disappear and all solutions will provided (now you lost cos(0) answer).
Level III, Task 1 done right 👍 


You have 2 attempts left.

**Comment by dmitryakimov2206283** [comment]
I changed conditions. I made them a bit different to allow variable x to be negative.

```c#
if (double.TryParse(Console.ReadLine(), out x))
{
    if (x == 0)
    {
        s = 1;
    }
    else
    {
        s = Math.Cos(x);
        double xPow = x;

        for (int i = 1; i <= 8; i++)
        {
            s += Math.Cos((i + 1) * x) / xPow;
            xPow *= x;
        }
    }

    Console.WriteLine($"Task 4: {Math.Round(s, 3)}\n");
}
```

**Comment by dmitryakimov2206283** [comment]
But I have no idea why we get any result with `x = 0`

MH8Qcqv3Teg

**Comment by NemirovichMark** [comment]
I ment that if (x==0) answer can be uptut as 1. Programming no so strict as math, there can be separate solutions of one task.

But as far as you provide so beatiful arguments I accept your work.
You can defend 1st lab next lesson.

Also you can make fork, solve 2nd lab and send your answer:
https://github.com/NemirovichMark/2nd_Lab

**Pull request merged**
