### PR TITLE
Create 1lab

### PR DESCRIPTION
**Pull request by RomaNazarenko**
Is everything OK?

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Roman.

#region Task 1.4 DivisionByZero

 #region Task 3.1 & #region Task 3.9
DRY - don't repeat yourself!

while (a * (-x * x / (2 * i * (2 * i - 1)))>0.0001)
                    {
                        a *= (-x * x / (2 * i * (2 * i - 1)));
Use a variable and do{}while instead

a *= a * -(x * x * (2 * i - 1) / (2 * (i - 1) - 1)); - you multiply a twice)
and why such formula? It should be easier.

Actually it is good that you make it as a recursion.

**Comment by RomaNazarenko** [comment]
Anyway, Can I defend my lab?

вт, 27 сент. 2022 г., 16:46 Mark ***@***.***>:

**Comment by NemirovichMark** [comment]
Not yet.
Fix all errors firstly.

**Comment by RomaNazarenko** [comment]
Could you repeat please where mistakes are and what I should change? I
don't understand)

вт, 27 сент. 2022 г., 17:33 Mark ***@***.***>:

**Comment by NemirovichMark** [comment]
Hello Roman.

#region Task 1.4 DivisionByZero
s += ((Math.Cos(i * x)) / (Math.Pow(x, i - 1)));

#region Task 3.1 & #region Task 3.9
DRY - don't repeat yourself!

while (a * (-x * x / (2 * i * (2 * i - 1)))>0.0001)
{
a *= (-x * x / (2 * i * (2 * i - 1)));

Use a variable and do{}while instead

#region Task 3.9 Wrong answer
a *= a * -(x * x * (2 * i - 1) / (2 * (i - 1) - 1)); - you multiply a twice)
Why such formula? It should be easier (I know it can be).

**Comment by RomaNazarenko** [comment]
Well. Check my update. But still I don't understand where is Division By Zero in the 1.4 Taska as there is no any errors in console. Also I changed Task 3.9 but the answer looks incorrect) Help please

**Comment by RomaNazarenko** [comment]
Hello, if I'm not mistaken, I made a comment to pull request that I changed
my program. Do you see it?

вт, 27 сент. 2022 г., 23:23 Mark ***@***.***>:

**Comment by NemirovichMark** [comment]
Hello Roman.

#region Task 1.4 DivisionByZero (when user inputs 0)
if (int.TryParse(Console.ReadLine(), out int x))
                {
                    for (i = 1; i <= 9; i++)
                    {
                        s += ((Math.Cos(i * x)) / (Math.Pow(x, i - 1)));

If you see ? in the console, it means your IDE automatically hide this error. You can turn it of in the settings.

You have to awoid this problem (either with if-statement or try/catch block)

Okay, I will accept it, so you can come to class to defend 1st lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/2nd_Lab

**Pull request merged**
