### PR TITLE
 lab №1

### PR DESCRIPTION
**Pull request by EgorPetko**

### CODE REVIEW

**Comment by EgorPetko** [comment]
lab №1

**Comment by NemirovichMark** [comment]
Hello Egor.

Do not use 3-nested cycle!
Change it to recursive formula:
for (int j = 2; j <= i * 2; ++j)
                    {
                        fact *= j;
                    }

You have 2 attempts left.

**Comment by EgorPetko** [comment]
update task 3_1

**Comment by NemirovichMark** [comment]
Good.
You can come to class to defend 1st lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/2nd_Lab

**Pull request merged**
