### PR TITLE
1st_Lab(Actually)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Andrey. 

1.9 StackOverFlow. Do not use recursive methods. Use recursive formula. It is when you use already calculated value (in the cycle). Do not use separate cycle for factorial calculation only. Look at the example in the Theory.cs
static int Factorial(int f)
        {
            if (f == 0)
            {
                return 1;
            }
            else
            {
                return f * Factorial(f-1); 
            }

The same ERROR in the 1.15 & 3.1 & 3.7

2.7 Excellent!
Everything else done well.
Please, remake 1.9, 1.15, 3.1, 3.7 without recursive method.

**Comment by ghost** [comment]
fixed

>why u dont like recursion 
why u dont like
why u dont 
why u
why

**Comment by NemirovichMark** [comment]
It consume a lot of memory. PC allocate some volume of DRAM for your exercise (when you run your program) named as STACK. And each call of recursive method fix some of this memory and keep till all branches would added. And than PC close it one by one. But memory can be run out.
image

But now you make another mistake)
PC too much consuming:
for (int j = 2*i; j >= 1; j--)
                {
                    Factorial *= j;
                }
You are recalculating the factorial every time from 1 to j. In the assignment, the lecturer was asked not to do this. Reuse an already computed value. Don't create a new cycle for it.

image

**Comment by ghost** [comment]
Copypaste textbook formula
It seems to be working (But actually, it promotes a slightly different answer to 3.1), but I cant really get it
Nevertheless, I'll try my best to understand the idea

**Comment by NemirovichMark** [comment]
Hello.
It is right.
 s = -s_prev * ((Math.Pow(x,2)) / ((2*i-1) * (2*i)));
because
i = 1:
fact = (2i)! = 2 * 1
i = 2
fact = (2i)! = 4 * 3 * 2 * 1 = 4 * 3 * fact (previously calculated)

You can come to class to defend 1st lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/2nd_Lab

**Pull request merged**
