### PR TITLE
Create 1st_lab_1_attempt

### PR DESCRIPTION
**Pull request by amirnizamiev**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Amir.

1.4 Do not use Math.Pow here:
z = Math.Cos(i * x) / Math.Pow(x, i - 1);
You have to use recursion: keep the calculated value and change it.
You recalculate it every time. It is not effective.
In next 2 tasks you solve with recursive formulas, actually (for factorial) and numerator & denominator

1.15 Wrong answer. Read the task more attentively
znamenatel += 1; - is wrong

1.16 Do not useMath.Pow(2, i);
1.18 Do not useMath.Pow(2, i);

2.2 Wrong answer. You have to provide previous element of your sequence. In your case you provide an element, when geometric progression becomes more than 30000. Expected: when it is less.

3.1 No need in Math.Pow here:
Math.Pow(i, 2)
i * i

3.4 The same:
Math.Pow(x, 2)

**Comment by NemirovichMark** [comment]
Eliminate Math.Pow here:
1.4 
1.16
2.2
if (p > 30000) - always true. Remove it.

**Comment by amirnizamiev** [comment]
Idk how to delete Math.Pow in my code. Everything else i've done. Can i send you version with math.pow, pls?

**Comment by NemirovichMark** [comment]
You no need to use i always for calculation. Cycle can be used for repeating any command.

for (i = 1; i <= 9; i++)
            {
                s = s + Math.Cos(i * x) / Math.Pow(x, i - 1);
            }

->

int denominator = 1;
for (i = 0; i <= 9; i++)
 {
s += cos(x*i)/denominator;
denominator *= x;
}

since denominator increases after summing it is the same as i-1 degree.

Try to implement such principle to 1.16

**Comment by NemirovichMark** [comment]
I've accepted newer branch.

**Pull request closed without merging**
