### PR TITLE
1st_Lab

### PR DESCRIPTION
**Pull request by PankovDaniil**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Daniil.

Good work!
1.15 Excellent solution!
2.4 Excellent solution!
1.16 Better to use i*i instead Pow(i, 2). It less consuming (also i*i*i instead Pow(i,3)). If pow>3 or double better to use it.
2.7-8 Can be made in one loop and get the result according to conditions. It has sense with big cycles' iterations (>10000)

Remake:
3.1 Recalculation of fractal from start every time very unefficient. As lector asked, use recursive formula instead.

You have 3 attempts left.

**Comment by PankovDaniil** [comment]
`double total = 0;
            for (double x2 = 0.1; x2 <= 1; x2 += 0.1)
            {
                x2 = Math.Round(x2, 1);
                total = 0;
                double cikl = 0;
                int i = 0;
                double factarial = 1;
                do
                {   
                    cikl = Math.Pow(-1, i) * Math.Pow(x2, (2*i)) / factarial;
                    i++;
                    total += cikl;
                    factarial *= 2 * i * (2 * i - 1);
                }
                while (cikl >= 0.0001);
                double y = Math.Cos(x2);
                Console.WriteLine($"x = {x2}; s = {total:f6};  y = {y:f6}");

            }`

**Comment by PankovDaniil** [comment]
```
            #region Num_1
            double total = 0;
            for (double x2 = 0.1; x2 <= 1; x2 += 0.1)
            {
                x2 = Math.Round(x2, 1);
                total = 0;
                double cikl = 0;
                int i = 0;
                double factarial = 1;
                do
                {   
                    cikl = Math.Pow(-1, i) * Math.Pow(x2, (2*i)) / factarial;
                    i++;
                    total += cikl;
                    factarial *= 2 * i * (2 * i - 1);
                }
                while (cikl >= 0.0001);
                double y = Math.Cos(x2);
                Console.WriteLine($"x = {x2}; s = {total:f6};  y = {y:f6}");

            }
            #endregion
```

**Comment by NemirovichMark** [comment]
Well done Daniil.

You can defend the 1st lab in the class next lesson. 
And you can make a fork and send 2nd lab here (in your branch):
https://github.com/NemirovichMark/2nd_Lab

**Pull request merged**
