### PR TITLE
Update Invitation

### PR DESCRIPTION
**Pull request by Toliyy**
I made levels 1 and 2.
I do not know how the 3rd level is solved mathematically. 
How do I protect myself?

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Anatoly.

1.16 Wrong answer
2.2 Wrong answer
Ask me in the class about 3rd task.

You have 2 attempts left.

**Comment by Toliyy** [comment]
Hello Mark, I fixed the errors and made the 3rd part!

**Comment by NemirovichMark** [comment]
Hello Anatoly.

2.2 Still wrong answer. You asked to provide last term when a product less than 30000.
3.1 You miss half of values. You count only even terms. Should be all. 
znak always = -1
you calculate (i)! , the task was (2i)!

Fix it, please.

Everything else done well.

**Comment by Toliyy** [comment]
Hello. I fixed a bug in 2.2 and hope I got it right and fixed a bug in 3.1

**Comment by NemirovichMark** [comment]
Good job!

You can come to class to defend 1st lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/2nd_Lab

**Pull request merged**
