### PR TITLE
Lab

### PR DESCRIPTION
**Pull request by KovalevNikolay710**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Nikolay.

1.4 DivisionByZero:
s = Math.Cos(x * n) / Math.Pow(x, n - 1) + s;
Task 1.9 StackOverFlow:
int Factorial(int i)
Don't use the recursive method. It allocates memory for the stack on each call and calculates the value each time from the beginning. Use a recursive formula that reuses already calculated variables.
Tasks 2.2 if (p * n < L) - exceeding condition (but it is not mistake)
Task 3.1 StackOverFlow:
double Factorial(double i) - change as 1.9

You have 2 attempts left.

**Comment by NemirovichMark** [comment]
Good.

**Comment by NemirovichMark** [comment]
You can come to class to defend 1st lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/2nd_Lab

**Comment by KovalevNikolay710** [comment]
But I've already defended 
--
Отправлено из Mail.ru для Android вторник, 20 сентября 2022г., 15:25 +03:00 от Mark  ***@***.*** :

**Comment by NemirovichMark** [comment]
I know. It is just a template. You can check in the the 1st_Lesson. Progress file.

**Pull request merged**
