### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by UlichniyPoz**
1st lab is done

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Ilya.

1.4 DivisionByZero
 s += Math.Cos(x * i) / Math.Pow(x, i - 1);

2.2. Wrong answer. In the task requires the last element when product less than 30 000. You provide when it already more.
Console.WriteLine(n);

3.1 Wrong answer (factorial) and wrong solution (not recursion). Calculate it with addictive value of new term of sequence, not as  a new value.
double j = Math.Pow(-1, i);
double k = Math.Pow(x, 2 * i);
double s = (j * k) / z;
 z = z * (i * 2 + 1) * (i * 2 + 2);

3.5 Wrong solution (not recursion). 
 double j = Math.Pow(-1, i);
 double k = Math.Cos(i * x);
double z = Math.Pow(i, 2);
double s = (j * k) / z;

**Comment by NemirovichMark** [comment]
Good job. You solution is very unordinary, cool!

You can come to class to defend 2nd lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/3rd_Lab

**Comment by UlichniyPoz** [comment]
я сдал пока что только первую лабораторную работу



Отправлено из мобильной Почты Mail.ru


пятница, 30 сентября 2022 г., 15:27 +0300 от ***@***.***  ***@***.***>:

**Comment by NemirovichMark** [comment]
You can submit up to 10 labs on Github even today and then defend them in class one by one.

**Pull request merged**
