### PR TITLE
1st_lab

### PR DESCRIPTION
**Pull request by dkarasevgthub**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Dmitry.

Task 1.4 DivisionByZero:
s += (Math.Cos(i * x) / Math.Pow(x, i - 1));
Task 1.9 StackOverFlow:
 s += (Math.Pow(-1, i) * Math.Pow(5, i) / factorial(i));
Don't use the recursive method. It allocates memory for the stack on each call and calculates the value each time from the beginning. Use a recursive formula that reuses already calculated variables.
Task 2.2 Wrong answer
Task 3.1 StackOverFlow:
term = Math.Pow(-1, i) * Math.Pow(xx, i * 2) / factorial(i * 2);
Task 3.7 StackOverFlow:
term = Math.Pow(xx, i * 2) / factorial(i * 2);

You have 2 attempts left.

**Comment by dkarasevgthub** [comment]
Hello, solution updated!

**Comment by NemirovichMark** [comment]
Still: errors:

Task 1.9 StackOverFlow:
s += (Math.Pow(-1, i) * Math.Pow(5, i) / factorial(i));
Task 3.1 StackOverFlow:
term = Math.Pow(-1, i) * Math.Pow(xx, i * 2) / factorial(i * 2);
Task 3.7 StackOverFlow:
term = Math.Pow(xx, i * 2) / factorial(i * 2);

You have 1 attempt left.

**Comment by dkarasevgthub** [comment]
Can you explain me how to fix this error on our class? Can I defend lab after that?

**Comment by NemirovichMark** [comment]
Of course I will

**Comment by dkarasevgthub** [comment]
Solution updated

**Comment by NemirovichMark** [comment]
It is 2*(i)!
Not a (2i)!
fac *= i;
term = Math.Pow(-1, i) * Math.Pow(xx, i * 2) / (fac * 2);

The same error at 3.7;

Remake!

**Comment by dkarasevgthub** [comment]
Solution updated!!!!

**Comment by NemirovichMark** [comment]
I little mistake in the formula (/2) but never mind.

You can come to class to defend 1st lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/2nd_Lab

**Pull request merged**
