### PR TITLE
Create 1st lab

### PR DESCRIPTION
**Pull request by BrekotkinaKarina**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
1.4 DivisionByZero occurred.
1.18 Wrong answer (and solution easier, actually)
3.1 & 3.7 Wrong factorial calculation.

**Comment by NemirovichMark** [comment]
3.1 & 3.7
You calculate 2*(i)! now
I expect (2i)!

**Review by BrekotkinaKarina — COMMENTED** [review]
factor = factor * (2 *i)

**Comment by NemirovichMark** [comment]
Nope

**Comment by BrekotkinaKarina** [comment]
factor = factor * 2 * (i+1)

**Comment by BrekotkinaKarina** [comment]
factor = factor * 2 * (i-1)

**Comment by NemirovichMark** [comment]
good

**Comment by NemirovichMark** [comment]
You can come to class to defend 1st lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/2nd_Lab

**Pull request merged**
